# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build-job:
    docker:
      - image: circleci/node:8.11.4@sha256:bba459fbda15808483daa60bfebff8ec5406ae9bfe5608bff5c72f65c3a6e1e5

    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test
      - run: yarn lint
      - run: yarn build
      - run: yarn prettier-check

  deploy-job:
    docker:
      - image: circleci/node:8.11.4@sha256:bba459fbda15808483daa60bfebff8ec5406ae9bfe5608bff5c72f65c3a6e1e5
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - run: yarn semantic-release

workflows:
  version: 2
  build-deploy:
    jobs:
      - build-job
      - deploy-job:
          requires:
            - build-job
          filters:
            branches:
              only: master
